before_deploy:
  - rvm requirements
  - rvm install 2.6
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

language: java

jdk:
  - openjdk8

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "bookstore-yunbin"